language: minimal

branches:
  only:
    - travis

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose run nicocourts/learning-docker
  - docker-compose ps -a

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: travis
