language: minimal

branches:
  only:
    - travis

services:
  - docker

before_install:
  - docker build -t nicocourts/testing-docker .
  - docker ps -a

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: travis
