version: '3.1'

services:

  letsencrypt-nginx-container:
    container_name: 'nicocourts/learning-docker'
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/usr/share/nginx/html
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
